In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
b=np.array([3,4,5])

In [4]:
a+b

array([4, 6, 8])

In [5]:
a*b

array([ 3,  8, 15])

In [6]:
a-b

array([-2, -2, -2])

In [7]:
a

array([1, 2, 3])

In [8]:
b =np.ones((3,4))

In [9]:
b+a

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [11]:
a.shape

(3,)

In [12]:
b.shape

(3, 4)

In [13]:
a=a[:,np.newaxis]

In [14]:
a.shape

(3, 1)

In [15]:
a

array([[1],
       [2],
       [3]])

In [16]:
a=np.array([1,2,3])

In [17]:
a=a[np.newaxis,:]

In [18]:
a.shape

(1, 3)

In [19]:
b.shape

(3, 4)

In [20]:
b+a

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 